services:
  db:
    image: postgres:14
    container_name: sensei-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-2rligaoi}
      POSTGRES_DB: ${DB_NAME:-sensei_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: sensei-app
    restart: always
    depends_on:
      - db
    # 解決 NameResolutionError，強制使用 Google DNS
    dns:
      - 8.8.8.8
      - 8.8.4.4
    env_file:
      - .env
    ports:
      - "8503:8501"
    volumes:
      - .:/app
    command: streamlit run src/app.py --server.port 8501 --server.address 0.0.0.0

volumes:
  postgres_data: